### ISSUE TITLE
bug: [Android] Error - Unsupported locale on Samsung smartphones

### ISSUE THREAD

**Issue by Warcreed** [capacitor-community/text-to-speech#63]
**Describe the bug**
Hi, got Unsupported locale while using this plugin on Samsung devices. Using getSupportedLanguages() on these devices returns ISO 639‑2 (or -3) standard language code. Screenshot linked below.

**Expected behavior**
I expect getSupportedLanguages() returns standardize language codes to use in locale property in speak function.

**Screenshots**
![image](https://user-images.githubusercontent.com/32953565/114517991-2e625100-9c3f-11eb-8478-99b7db5e89c5.png)

**Smartphone:**
- Device: [Galaxy A8, Galaxy A41 ]
- OS: [Android 9 and Android 10]

**Additional context**
I am using Capacitor 2 and text-to-speech v0.2.3, as in Readme specified.

**Workaround**
As workaround, i made it work commenting the supportedLocales check here below and hard coding standardize IETF language tag code like "en-US", but it is not a stable workaround obviously:
![image](https://user-images.githubusercontent.com/32953565/114520921-396ab080-9c42-11eb-936e-5ac4af46ed1b.png)

**Comment by robingenz** [comment]
Hi, this bug should already be fixed with #58.
Unfortunately the fix is only available since version `1.1.0` (Capacitor 3).
You can test the latest version of the plugin with the following demo app: https://github.com/robingenz/capacitor-plugin-demo

Please reopen this issue if the bug still exists in the latest version.
